
# (PART) Applications in Genomics {-} 

# Introduction {#genomic-introduction}

Since circos plots are mostly used in genomic research, the \textbf{circlize} package 
particularly provides functions which focus on genomic plots. These functions 
are synonymous to the basic circos graphic functions but expect special format of input data:

\begin{itemize}
  \item {\tt circos.genomicTrackPlotRegion}: create a new track and add graphics.
  \item {\tt circos.genomicPoints}: low-level function, add points
  \item {\tt circos.genomicLines}: low-level function, add lines
  \item {\tt circos.genomicRect}: low-level function, add rectangles
  \item {\tt circos.genomicText}: low-level function, add text
  \item {\tt circos.genomicLink}: add links
\end{itemize}

The genomic functions are implemented by basic circos functions (e.g. {\tt circos.trackPlotRegion}, {\tt circos.points}),
thus, you can customize your own plots by both genomic functions and basic circos functions.

\section{Input data}

Genomic circos functions expect input data as a data frame or a list of data frames 
in which there are at least three columns. The first column is genomic category 
(e.g. chromosome), the second column is the start positions in the genomic category and 
the third column is the end positions. Following columns are optional where numeric values 
or other related values are stored. Such data structure is known as {\it BED} format 
and is broadly used in genomic research.

\textbf{circlize} provides a simple function {\tt generateRandomBed} which can generate 
random genomic data. Positions are uniformly generated from human genome and the number 
of regions on chromosomes approximately proportional to the length of chromosomes. 
In the function, {\tt nr} and {\tt nc} are number of rows and numeric columns that 
users want. Please note {\tt nr} are not exactly the same as the number of rows which 
are returned by the function. {\tt fun} is a self-defined function to generate random values.

<<>>=
library(circlize)
set.seed(999)

bed = generateRandomBed()
head(bed)
bed = generateRandomBed(nr = 200, nc = 4)
nrow(bed)
bed = generateRandomBed(nc = 2, fun = function(k) runif(k))
head(bed)
@
